// frontend development/Kurapati Vishnu Vardhan Reddy/handson_07/student-portal-angular/src/app/course-card/course-card.ts
import { Component,Input } from '@angular/core';

@Component({
  selector: 'app-course-card',
  imports: [],
  templateUrl: './course-card.html',
  styleUrl: './course-card.css',
})
export class CourseCard {

  @Input() name: string = '';
  @Input() code: string = '';
  @Input() credits: number = 0;
  @Input() grade: string = '';

}

// frontend development/Kurapati Vishnu Vardhan Reddy/handson_05/src/components/CourseCard.jsx
import "./css/CourseCard.css";

function CourseCard({ name, code, credits, grade,setEnrolledCourse }) {
    return (
        <article className="course-card">
            <h2>{name}</h2>
            <p>Code: {code}</p>
            <p>Credits: {credits}</p>
            <p>Grade: {grade}</p>
            <button onClick={() => setEnrolledCourse(prev => [...prev, { name, code, credits, grade }])}>Enroll</button>
        </article>
    );
}

export default CourseCard;
